/**
* @File Name : InventoryController .cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : December 10, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | December 10, 2025 |   | Initial Version
**/

public class InventoryController  {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}